name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Configure Gradle Network Settings
        run: |
          mkdir -p ~/.gradle
          cat >> ~/.gradle/gradle.properties << 'EOF'
          systemProp.http.socketTimeout=120000
          systemProp.http.connectionTimeout=120000
          systemProp.https.socketTimeout=120000
          systemProp.https.connectionTimeout=120000
          org.gradle.daemon=false
          EOF

      - name: build
        run: |
          for attempt in {1..3}; do
            echo "Build attempt $attempt of 3"
            if ./gradlew build --stacktrace --no-daemon --refresh-dependencies; then
              echo "Build succeeded on attempt $attempt"
              exit 0
            fi
            if [ $attempt -lt 3 ]; then
              echo "Build failed, waiting 30 seconds before retry..."
              sleep 30
            fi
          done
          echo "Build failed after 3 attempts"
          exit 1

      - name: capture build artifacts
        if: ${{ matrix.java == '21' }}
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
